---
version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/base:2021.04
    working_directory: ~/checkout
    environment:
      SSH_HOST: "<< pipeline.parameters.HOST >>"
      SSH_USER: "<< pipeline.parameters.USER >>"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a4:73:dd:6f:7f:b5:87:36:f3:d8:43:ac:df:d9:82:c9"
      - checkout
      - run:
          name: Edit ansible playbook
          command: |
             bash config_playbook.sh
      - run:
          name: Send ansible directory to public instance (from checkout)
          command: |
             scp -r ./ansible "$SSH_USER@$SSH_HOST:/home/$SSH_USER"                    
      - run:
          name: Run ansible playbook
          command: |
             ssh $SSH_USER@$SSH_HOST "cd ansible; ansible-playbook playbook.yaml"

# Here we set host & user details.
parameters:
  HOST:
    default: "3.65.112.253"
    type: string
  USER:
    default: ubuntu
    type: string

# Here we ordering the jobs.
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main