---
version: 2.1
jobs:
  deploy:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    working_directory: ~/checkout
    steps:
      - checkout
      - run:
          name: check basic staff
          command: |
             pwd
             ls
      - run:
          name: Install ansible on puclic instance
          command: |
             ssh $SSH_USER@$SSH_HOST "hostname; sudo apt-get update; sudo apt install ansible -y"
      - run:
          name: Edit ansible playbook
          command: |
             sudo apt-get install jq -y
             bash config_playbook.sh
      - run:
          name: Send ansible directory to public instance (from checkout)
          command: |
             scp -r ./ansible "$SSH_USER@$SSH_HOST:/home/$SSH_USER"                    
      - run:
          name: Run ansible playbook
          command: |
             ssh $SSH_USER@$SSH_HOST "cd ansible; ansible-playbook playbook.yaml"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main